apiVersion: v1
kind: Service
metadata:
  name: confluence-server
  labels:
    app: confluence-server
spec:
  ports:
    - port: 8090
  selector:
    app: confluence
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluence
  labels:
    app: confluence
spec:
  selector:
    matchLabels:
      app: confluence
  replicas: 1
  template:
    metadata:
      labels:
        app: confluence
    spec:
      containers:
        - name: confluence
          imagePullPolicy: IfNotPresent
          image: "atlassian/confluence-server:7"
          ports:
            - containerPort: 8090
              name: http
            - containerPort: 8091
              name: synchrony
          volumeMounts:
            - name: datadir
              mountPath: /var/atlassian/application-data/confluence
      volumes:
        - name: datadir
          hostPath:
            path: /var/lib/k8s/development/confluence