apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          imagePullPolicy: IfNotPresent
          image: "postgres:9.4"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: datadir
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: datadir
          hostPath:
            path: /var/lib/k8s/development/postgres